apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: samvelantanyan/ticketing-auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.ts'
            dest: .
    - image: samvelantanyan/ticketing-client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: samvelantanyan/ticketing-tickets
      context: ./tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.ts'
            dest: .
    - image: samvelantanyan/ticketing-orders
      context: ./orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.ts'
            dest: .
    - image: samvelantanyan/ticketing-expiration
      context: ./expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './src/**/*.ts'
            dest: .
